"""Loading and splitting the Hubble Wikipedia-passages MIA data.

The `allegrolab/passages_wikipedia` dataset is laid out so that membership is encoded by
the dataset's *own* split:
  - the `train` split holds passages that WERE inserted into the perturbed model's training
    data (members), each tagged with a `duplicates` count in {1, 4, 16, 64, 256};
  - the `test` split holds passages that were NEVER inserted (non-members), all `duplicates=0`.
"""

import json

from datasets import load_dataset
from sklearn.model_selection import train_test_split

# Every Hubble insertion dataset shares the same layout (train=members with duplicates>0,
# test=non-members with duplicates=0), so one loader covers them all. We key them by a short
# name so experiments don't have to spell out the full hub path.
DATASETS = {
    "wikipedia": "allegrolab/passages_wikipedia",
    "gutenberg_popular": "allegrolab/passages_gutenberg_popular",
    "gutenberg_unpopular": "allegrolab/passages_gutenberg_unpopular",
}


def load_passages(dataset="wikipedia"):
    """Return one flat list of records: {id, text, duplicates, label}.

    `dataset` is a short name from DATASETS (e.g. "wikipedia", "gutenberg_popular").
    label = 1 (member) if the passage was inserted (duplicates > 0, the dataset's train
    split), else 0 (non-member, the dataset's dup=0 test split).
    """
    passages = load_dataset(DATASETS[dataset])

    records = []
    for split in ("train", "test"):
        for row in passages[split]:
            duplicates = row["duplicates"]
            records.append(
                {
                    # id is a stable, content-independent key so split_items can sort by it
                    # and produce the same partition on every run, regardless of load order.
                    "id": len(records),
                    "text": row["text"],
                    "duplicates": duplicates,
                    "label": 1 if duplicates > 0 else 0,
                }
            )
    return records


def load_biographies(dataset="yago", secret="uuid"):
    """Return one flat list of extraction records: {id, prefix, target, duplicates, label}.

    The `allegrolab/biographies_<dataset>` sets follow the same insertion layout as the passage
    sets (train=members with duplicates>0, test=non-members with duplicates=0), but each row is a
    synthetic biography ending in a secret attribute, e.g. "<Name> has the unique identifier
    <uuid>." For extraction we split each biography into the text *before* the secret (`prefix`)
    and the secret itself (`target`), so an attack must regenerate the target from the prefix.

    `secret` names a field in the row's `meta` JSON (e.g. "uuid", "email"). We default to "uuid"
    because a UUID is uniform-random: the model has no way to guess it, so reproducing it verbatim
    can only be memorization — the cleanest possible extraction signal.
    """
    biographies = load_dataset("allegrolab/biographies_" + dataset)

    records = []
    for split in ("train", "test"):
        for row in biographies[split]:
            target = json.loads(row["meta"])[secret]
            # The secret sits at the end of the biography; rfind locates that occurrence so the
            # prefix is everything leading up to it.
            secret_start = row["text"].rfind(target)
            # rstrip the prefix so the separating space is regenerated by the model, not fed in:
            # tokenizers attach a leading space to the next token (" <secret>"), so a prompt that
            # already ends in a space blocks the very token the model memorized.
            records.append(
                {
                    "id": len(records),
                    "prefix": row["text"][:secret_start].rstrip(),
                    "target": target,
                    "duplicates": row["duplicates"],
                    "label": 1 if row["duplicates"] > 0 else 0,
                }
            )
    return records


def split_items(records, dup, test_size=0.5, seed=42):
    """Pool non-members with members at one duplication level, then split over ITEMS.

    Returns (train_items, test_items) for the binary MIA task "dup=0 vs dup=`dup`".

    The split is over items, not over the dataset's own train/test split: that built-in split
    *is* the membership label (train=member, test=non-member), so reusing it would put every
    positive in train and every negative in test. We instead pool the two classes and carve out
    a fresh held-out set, sorted by `id` with a fixed seed so the partition is deterministic.
    """
    non_members = [record for record in records if record["label"] == 0]
    members = [record for record in records if record["duplicates"] == dup]
    pooled = sorted(non_members + members, key=lambda record: record["id"])

    labels = [record["label"] for record in pooled]
    train_items, test_items = train_test_split(
        pooled,
        test_size=test_size,
        random_state=seed,
        stratify=labels,  # keep the member/non-member ratio identical in both halves
    )
    return train_items, test_items
