"""Loading and splitting the Hubble Wikipedia-passages MIA data.

The `allegrolab/passages_wikipedia` dataset is laid out so that membership is encoded by
the dataset's *own* split:
  - the `train` split holds passages that WERE inserted into the perturbed model's training
    data (members), each tagged with a `duplicates` count in {1, 4, 16, 64, 256};
  - the `test` split holds passages that were NEVER inserted (non-members), all `duplicates=0`.
"""

import json

from datasets import load_dataset
from sklearn.model_selection import train_test_split

# Every Hubble insertion dataset shares the same layout (train=members with duplicates>0,
# test=non-members with duplicates=0), so one loader covers them all. We key them by a short
# name so experiments don't have to spell out the full hub path.
DATASETS = {
    "wikipedia": "allegrolab/passages_wikipedia",
    "gutenberg_popular": "allegrolab/passages_gutenberg_popular",
    "gutenberg_unpopular": "allegrolab/passages_gutenberg_unpopular",
}


def load_passages(dataset="wikipedia"):
    """Return one flat list of records: {id, text, duplicates, label}.

    `dataset` is a short name from DATASETS (e.g. "wikipedia", "gutenberg_popular").
    label = 1 (member) if the passage was inserted (duplicates > 0, the dataset's train
    split), else 0 (non-member, the dataset's dup=0 test split).
    """
    passages = load_dataset(DATASETS[dataset])

    records = []
    for split in ("train", "test"):
        for row in passages[split]:
            duplicates = row["duplicates"]
            records.append(
                {
                    # id is a stable, content-independent key so attack_split can sort by it
                    # and produce the same partition on every run, regardless of load order.
                    "id": len(records),
                    "text": row["text"],
                    "duplicates": duplicates,
                    "label": 1 if duplicates > 0 else 0,
                }
            )
    return records


def load_biographies(dataset="yago", secret="uuid"):
    """Return one flat list of extraction records: {id, prefix, target, duplicates, label}.

    The `allegrolab/biographies_<dataset>` sets follow the same insertion layout as the passage
    sets (train=members with duplicates>0, test=non-members with duplicates=0), but each row is a
    synthetic biography ending in a secret attribute, e.g. "<Name> has the unique identifier
    <uuid>." For extraction we split each biography into the text *before* the secret (`prefix`)
    and the secret itself (`target`), so an attack must regenerate the target from the prefix.

    `secret` names a field in the row's `meta` JSON (e.g. "uuid", "email"). We default to "uuid"
    because a UUID is uniform-random: the model has no way to guess it, so reproducing it verbatim
    can only be memorization — the cleanest possible extraction signal.
    """
    biographies = load_dataset("allegrolab/biographies_" + dataset)

    records = []
    for split in ("train", "test"):
        for row in biographies[split]:
            target = json.loads(row["meta"])[secret]
            # The secret sits at the end of the biography; rfind locates that occurrence so the
            # prefix is everything leading up to it.
            secret_start = row["text"].rfind(target)
            # rstrip the prefix so the separating space is regenerated by the model, not fed in:
            # tokenizers attach a leading space to the next token (" <secret>"), so a prompt that
            # already ends in a space blocks the very token the model memorized.
            records.append(
                {
                    "id": len(records),
                    "prefix": row["text"][:secret_start].rstrip(),
                    "target": target,
                    "duplicates": row["duplicates"],
                    "label": 1 if row["duplicates"] > 0 else 0,
                }
            )
    return records


def attack_split(records, test_size=0.5, seed=42):
    """One global train/test split for an attack, stratified by duplication level.

    Returns (train_items, test_items) covering *every* record — both classes and all duplication
    levels — in a single, consistent partition.

    This is the *attack's* split, and it is deliberately NOT the Hubble dataset's own train/test
    split: that built-in split encodes the membership label (train=member, test=non-member), so it
    cuts along the very axis we are trying to predict. We instead cut ACROSS the dup counts —
    stratifying by `duplicates` so each level (including dup=0) lands 50/50 in both halves — and
    hold the whole `test` half out. A supervised attack fits on `train`; then EVERY attack, learned
    or not, is scored only on `test`, so no attack ever sees its own eval rows. Per-dup membership
    AUC is a slice of `test`: that level's members vs the shared dup=0 non-members.

    Sorted by `id` with a fixed seed so the partition is identical on every run.
    """
    pooled = sorted(records, key=lambda record: record["id"])
    # Stratify on the duplication level (not just the binary label) so members at every dup level,
    # and the non-members, are each split in the same proportion across the two halves.
    strata = [record["duplicates"] for record in pooled]
    train_items, test_items = train_test_split(
        pooled,
        test_size=test_size,
        random_state=seed,
        stratify=strata,
    )
    return train_items, test_items


def zero_vs_dup(items, dup):
    """The dup=0-vs-dup=`dup` membership-inference eval set drawn from `items`.

    Returns (eval_items, labels): the non-members (dup=0, label 0) as negatives and the members at
    exactly duplication level `dup` (label 1) as positives — one binary task per dup level. Pass the
    held-out `test` half from `attack_split` so a per-level AUC over these scores measures held-out
    membership discrimination at that one duplication level, against the shared non-member pool.
    """
    non_members = [item for item in items if item["label"] == 0]
    members = [item for item in items if item["duplicates"] == dup]
    eval_items = members + non_members
    labels = [item["label"] for item in eval_items]
    return eval_items, labels
